name: Mediconnect Pokhara - CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: production
    strategy:
      matrix:
        node-version: [22.x]
    env:
      PROJECT_DIR: ${{ github.workspace }}
      CREDS_DIR: /home/abu/mediconnectpokhara.com
      NGINX_WEB_DIR: /var/www/html/mediconnectpokhara.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Copy credentials
        run: |
          cp $CREDS_DIR/.env $PROJECT_DIR/.env

      - name: Build the application
        run: npm run build

      - name: Copy build files to the respective filepath
        run: |
          sudo mkdir -p $NGINX_WEB_DIR
          sudo cp -r $PROJECT_DIR/dist/* $NGINX_WEB_DIR
